### ISSUE TITLE
Installing Plugin

### ISSUE THREAD

**Issue by User87123671263871263** [Yey007/Paper-Auto-Updater#1]
When trying to download the plugin it cannot read any file that is not a .jar file. I did some research through the files and found no .jar file for my system to pickup. A really good plugin to have though.

**Comment by utkudotdev** [comment]
Hey, sorry I'm so late to respond. I'm confused on what exactly your problem is, the steps to install are:
1. Go to "releases" on this github page
2. Download the latest release
3. Put it in your "plugins" folder
4. Run the server once so the files are created
5. Configure the plugin in config.yml
6. Run the server

**Comment by utkudotdev** [comment]
Anyways, I'll close this issue for now. You can reopen it if you're still curious.
