### ISSUE TITLE
Not an issue, but a question...

### ISSUE THREAD

**Issue by joex92** [Yey007/Paper-Auto-Updater#3]
Are you going to keep updating this? (haven't tried yet)
because this would be very useful to have... what you [posted in paper forum](https://webcache.googleusercontent.com/search?q=cache:5RftiowqNaAJ:https://papermc.io/forums/t/all-paper-versions-paperautoupdate-automatically-update-paper-jar-when-you-shut-down-your-server/3293+&cd=2&hl=en&ct=clnk&gl=ec) has been deleted, but thanks to google cache I could read it... 
Is using a script better than the plugin?

**Comment by utkudotdev** [comment]
Hello,
I just realized people still look here. This plugin or any auto update script isn't really a good idea. Unless you have full trust in bug free builds, I wouldn't use it. This project is no longer maintained and will soon be archived. If you really want an auto updater, use a script. They're pretty easy to write. If you're wondering why the post was deleted, I deleted it because I was no longer maintaining the project. In hindsight, maybe that wasn't a great move, because there was other valuable information there. Sorry about that.
Regards,
Yey007
